/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
 * This code was autogenerated by RooClassFactory                            *
 *                                                                           * 
 * Authors:                                                                  *
 * Katherine George - University of Liverpool                                *
 * Adrian Bevan QMUL (ported from RptBaseTools to Roo - 2009)                *
 * Code massaged by Giulio Dujany - University of Manchester                 *
 *****************************************************************************/

#ifndef ROORELBREITWIGNER
#define ROORELBREITWIGNER

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class RooRelBreitWigner : public RooAbsPdf {
public:
  RooRelBreitWigner() {} ; 
  RooRelBreitWigner(const char *name, const char *title,
	      RooAbsReal& _x,
	      RooAbsReal& _mean,
	      RooAbsReal& _width,
	      RooAbsReal& _spin,
	      RooAbsReal& _radius,
	      RooAbsReal& _massa,
	      RooAbsReal& _massb);
  RooRelBreitWigner(const RooRelBreitWigner& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooRelBreitWigner(*this,newname); }
  inline virtual ~RooRelBreitWigner() { }

protected:

  RooRealProxy x ;
  RooRealProxy mean ;
  RooRealProxy width ;
  RooRealProxy spin ;
  RooRealProxy radius ;
  RooRealProxy massa ;
  RooRealProxy massb ;
  
  Double_t evaluate() const ;

private:
  Double_t Gamma() const;
  Double_t KFunction(Double_t X) const;
  Double_t FFunction(Double_t X) const;

  ClassDef(RooRelBreitWigner,1) // Your description goes here...
};
 
#endif
